name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🔎 Checkout
        uses: actions/checkout@v4

      - name: 🧪 Test
        run: cargo test --all-features

      - name: 💄 Format
        run: cargo fmt --all -- --check

      - name: 🧹 Clippy
        run: cargo clippy --all --all-features --tests -- -D warnings
